version: "3"
services:
       login-app:
           container_name: eyeblog
           image: eyeblog 
           restart: always
           build: .
           ports:
             - "5000:5000"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./eyesCool:/data/db
             ports:
               - '27018:27017'